### ISSUE TITLE
Stone cli prove-bootloader doesnt work

### ISSUE THREAD

**Issue by guha-rahul** [zksecurity/stone-cli#15]
If we run 
```
stone-cli prove-bootloader --cairo_programs ./examples/cairo0/bitwise_output.json --layout starknet --parameter_file ./tests/configs/bootloader_cpu_air_params.json --output bootloader_proof.json --fact_topologies_output fact_topologies.json
```
I am getting this output
```
Bootloader program output:
382450030162484995497251732956824096484321811411123989415157331925872358847
-1105634678291810840495795743566225907562315655840952488182375710141777272881
1
3
603813996395768983940956317134610857891217643068814355807758856063588214192
0
Running prover for bootloader...
Error: Failed to run stone prover: prover run failed
```
ps: i solve the cairo-proof-parser with a new updated package

**Comment by mellowcroc** [comment]
Could you try making the error more expressive by changing the `error.rs` code to the following and sharing the output?
```
    #[error("prover run failed: {0}")]
    CommandError(std::process::Output),
```

**Comment by guha-rahul** [comment]
Hey @mellowcroc , idk what happened but suddenly it worked for me . But do you plan to merge the cairo-proof-parser pr or are you finding some better alternatives.?
Also running the prover in m3 chip takes about 8mins and on M1 about 30 mins , doing something like `CPU_AIR_PROVER=<absolute path to binary>`

**Comment by mellowcroc** [comment]
> But do you plan to merge the cairo-proof-parser pr or are you finding some better alternatives.?

There's a PR now that uses a different lib and adds additional functionalities (https://github.com/zksecurity/stone-cli/pull/13). It will be merged soon, but feel free to work on that branch.

> Also running the prover in m3 chip takes about 8mins and on M1 about 30 mins , doing something like CPU_AIR_PROVER=<absolute path to binary>

What sure what you mean here, do you mean it's too slow?

**Comment by guha-rahul** [comment]
@mellowcroc Yes it takes about 30 mins on m1
