### ISSUE TITLE
Failed to prove my program with stone-cli

### ISSUE THREAD

**Issue by tdelabro** [zksecurity/stone-cli#27]
I'm was trying to prove using `cairo1-run` + `cpu_air_prover`. 
Bug on bug. I tried your tool and didn't worked either.
Mentioned here:
https://github.com/lambdaclass/cairo-vm/issues/1889#issuecomment-2525065749

Scroll up for more context.

I ran
```
stone-cli prove \
  --prover_config_file $CFG_AND_PARAMS_DIR/cpu_air_prover_config.json  \
  --cairo_program target/release/$PROGRAM_NAME.sierra.json \
  --program_input "[650157136941007917207724121471813482783483983289688285320161307177215463403 1655569645808460179723299787189716707852181277595105475126938070374837146371]" \
  --layout all-cairo \
  --output $PROOF_OUTPUT_DIR/proof.json 
  ```
  
  And used the main branch of the repo

**Comment by mellowcroc** [comment]
Marking this as duplicate of https://github.com/zksecurity/stone-cli/issues/29. Please reopen if I'm wrong.
